### ISSUE TITLE
FeedApi no exist ErrorList

### ISSUE THREAD

**Issue by ollscode** [web-com-pl/amazon-selling-partner-api-php#1]
Error in FeedApi.

Fatal error: Uncaught Error: Class '\Webcom\Amazon\Rest\FeedsApi\Model\ErrorList' not found in /var/www/vhost/amzapi.local/src/ObjectSerializer.php:364 Stack trace: #0 /var/www/vhost/amzapi.local/src/FeedsApi/Api/FeedsApi.php(1022): Webcom\Amazon\Rest\ObjectSerializer::deserialize() #1 /var/www/vhost/amzapi.local/src/FeedsApi/Api/FeedsApi.php(829): Webcom\Amazon\Rest\FeedsApi\Api\FeedsApi->createFeedDocumentWithHttpInfo() #2 /var/www/vhost/amzapi.local/examples/feeds.php(87): Webcom\Amazon\Rest\FeedsApi\Api\FeedsApi->createFeedDocument() #3 {main} thrown in /var/www/vhost/amzapi.local/src/ObjectSerializer.php on line 364

No exist FeedsApi\Model\ErrorList

**Comment by magik092** [comment]
@ollscode it have to be invalid model source. I will update all models to be up to date.
